trigger:
- main

pool:
  name: 'MyAgent'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test Job'
  steps:
  - checkout: self
    displayName: 'Checkout code'

  - script: |
      echo Hello from MyAgent!
      dir
    displayName: 'Run simple test script'
